name: Continous integration
on: [push, pull_request]
jobs:
  test:
    name: Run test & check code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: pecl
          extensions:
          coverage: pcov
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Test code style
        run: composer lint
      - name: Run tests
        run: composer test -- --coverage-clover coverage.xml --coverage-text
      - name: Get Ocular
        run: wget https://scrutinizer-ci.com/ocular.phar
      - name: Push code coverage
        run: php ocular.phar code-coverage:upload --format=php-clover coverage.xml
      - uses: actions/setup-node@v1
        node-version: '14.x'
      - name: Automated release
        run: npx semantic-release -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}